Search help page layout
ReCoded-Org/capstone-istanbul-safe_place pull request #61
Opened 2020-11-07 12:42 UTC by jennethydyrova

* Created layout for search help page 
* Changed single card class name from carouselItem to singleCard
* Added filter buttons without functionality. Functionality will be added in the next PR
* Svg color change on hover will be added in the next PR

<img width="1440" alt="Screen Shot 2020-11-07 at 15 39 45" src="https://user-images.githubusercontent.com/67760504/98441481-a74d0200-210f-11eb-82cf-a79f5e582399.png">

2020-11-07 17:40 UTC, Jamil-Bailony requested changes
I think you need to change the case of the images names to camelCase, check the translations, the see if you need to move the button style to global file. Thank you very much

2020-11-07 17:40 UTC, Jamil-Bailony commented on src/containers/SearchForHelpPage/index.jsx
> +        psychologist, lawyers or doctors
why did not you translate this one?

2020-11-07 17:40 UTC, Jamil-Bailony commented on src/containers/SearchForHelpPage/index.scss
> +    background-color: $lightColor !important;
I think you do not need important here

2020-11-07 17:40 UTC, Jamil-Bailony commented on src/containers/SearchForHelpPage/index.scss
> +    font-weight: bold;
if you see that this button will be used in another place, I suggest to move it to _buttons.scss file.

2020-11-07 17:40 UTC, Jamil-Bailony commented on src/images/icons/map-marker.svg
> +<svg width="13" height="16" viewBox="0 0 13 16" fill="none" xmlns="http://www.w3.org/2000/svg">
use camelCase in the image name

2020-11-07 17:40 UTC, Jamil-Bailony commented on src/images/Chevron-right.svg
> +</svg>
use camelCase in the file name as we use to.

2020-11-07 17:55 UTC, louisrli commented on src/containers/SearchForHelpPage/index.jsx
> +        psychologist, lawyers or doctors
typo in information

2020-11-07 18:09 UTC, jennetturkkan commented on src/containers/SearchForHelpPage/index.scss
> +    font-weight: bold;
no, it won't be

2020-11-07 18:10 UTC, jennetturkkan commented on src/containers/SearchForHelpPage/index.jsx
> +        psychologist, lawyers or doctors
@Jamil-Bailony I will add translation in the next PR along the functionality

2020-11-07 18:19 UTC, jennetturkkan commented on src/images/icons/map-marker.svg
> +<svg width="13" height="16" viewBox="0 0 13 16" fill="none" xmlns="http://www.w3.org/2000/svg">
it's being imported in camelCase anyway, but okay, i will change

2020-11-07 19:16 UTC, louisrli approved these changes

2020-11-07 19:16 UTC, louisrli commented on src/containers/SearchForHelpPage/index.jsx
> +          <Dropdown.Item eventKey="0">Istanbul</Dropdown.Item>
this is fine for now, but in the future

even for intermediate code this can make your life easier to change later. im assuming these get translated later

```
// or maybe you're loading using useObject later
const LOCATION_TRANSLATION_KEYS = ["istanbul", "ankara", "izmir"];
LOCATION_TRANSLATION_KEYS.map(key => <DropdownItem eventKey={key}>t(key)</DropdownItem>)
```

and the only difference between wiring in translations and not is that you take out the t() part.

2020-11-07 19:16 UTC, louisrli commented on src/containers/SearchForHelpPage/index.jsx
> +          <Dropdown.Item eventKey="1">Ankara</Dropdown.Item>
these event keys should be meaningful, like "istanbul" or "ankara" or something like htis. in general even if i were not translating i would use a map here. same with line 25.

the problem with 0, 1, 2, 3 is that it makes it harder to debug too when you console.log stuff ("wait what does 0 mean again?")

2020-11-07 19:16 UTC, louisrli commented on src/containers/SearchForHelpPage/index.jsx
> +        <DropdownButton title="Location">
{/* TODO add translations */} or some comment like this if you are doing them later

2020-11-07 19:34 UTC, Jamil-Bailony commented on src/components/SeekHelpSingleCard/__snapshots__/index.test.jsx.snap
>            alt="Location Icon"
icon with lower case as our master, Louis, once suggested

2020-11-07 19:36 UTC, jennetturkkan commented on src/containers/SearchForHelpPage/index.jsx
> +          <Dropdown.Item eventKey="0">Istanbul</Dropdown.Item>
the reason why I said that it will be added later is because I am already half-way through functionality of this component and I added translations there. But you are right, it would be more clear if I added translation in this PR.

2020-11-07 19:37 UTC, Jamil-Bailony reviewed
Please, change the Icon to icon in the alt, and fix the errors that case to not pass the tests

2020-11-07 20:12 UTC, jennetturkkan commented on src/containers/SearchForHelpPage/index.jsx
> +        <DropdownButton title="Location">
added translation in this PR

2020-11-07 20:13 UTC, Jamil-Bailony approved these changes

2020-11-07 20:59 UTC, louisrli approved these changes

2020-11-07 20:59 UTC, louisrli commented on src/containers/SearchForHelpPage/index.jsx
> +          <Dropdown.Item eventKey="0">Istanbul</Dropdown.Item>
actually i didn't mean that you have to add translation in this PR, but i meant they even if you will add it in a later PR you can "set up your code" so that its more changeable later as well (i often do this when writing intermediate steps in my code)

2020-11-08 11:10 UTC, jennethydyrova commented
@Ammar-64 can you please merge? i fixed netlify error

2020-11-08 11:11 UTC, merged